kind: stack

depends:
  - bluefin-nvidia/nvidia-drivers.bst
  - bluefin-nvidia/nvidia-vaapi-driver.bst
  - bluefin-nvidia/egl-external-platform.bst
  - bluefin-nvidia/nvidia-egl-wayland.bst
  - bluefin-nvidia/nvidia-kargs.bst
  - bluefin-nvidia/nvidia-modprobe-config.bst
  - bluefin-nvidia/nvidia-device-nodes.bst
  - bluefin-nvidia/nvidia-container-toolkit.bst
  - bluefin-nvidia/nvidia-container-toolkit-preset.bst
